#!/usr/bin/env bash

# Set the IP addresses for web-01 and web-02
WEB_01_IP="100.25.140.7"
WEB_02_IP="3.89.160.253"

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx
sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
       return 301 https://youtu.be/3_mt7qZldLs;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo service nginx restart

# Install and configure HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 $WEB_01_IP:80 check
    server web-02 $WEB_02_IP:80 check
EOF

# Restart HAProxy
sudo systemctl restart haproxy

