#!/usr/bin/env bash
# This script connects to the server using SSH with a private key

ssh -i ~/.ssh/school -o IdentitiesOnly=yes -o StrictHostKeyChecking=no ubuntu@7d2ec264a48a.07ddd36c.alx-cod.online

